### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by xlvlx** [weidengeist/Willowbot#11]
C:\programs\Willowbot>python main_cli.py
 × There is no logins file in your Willowbot configuration directory:
       C:\Users\xlvlx\AppData\Roaming\twitch\willowbot
   Will exit now. Have you configured Willowbot yet (--configure)?

**Comment by weidengeist** [comment]
This is no issue report. You have simply copied and pasted an error message, but you have not described any circumstances under which it appears nor given details about your configuration or steps to reproduce this issue.

The error message clearly states that you probably haven’t configured Willowbot yet. Please read the [README.md](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#2-initial-setup) to find out how to do so.

**Comment by xlvlx** [comment]
Windows 10, 64bitt, Python 3.12

**Comment by weidengeist** [comment]
Thanks for reporting. The issue should now be resolved with the [lastest commit](https://github.com/weidengeist/Willowbot/commit/ac5b56b645f53c1293d76decf8158fcde2c068f9).

**Comment by xlvlx** [comment]
well, we've definitely made progress, but there are still errors with the file. "config.py "
![Снимок экрана 2024-06-18 212629](https://github.com/weidengeist/Willowbot/assets/146260416/ce94bb7d-f79c-4473-8a92-a95794a52185)
![Снимок экрана 2024-06-18 212416](https://github.com/weidengeist/Willowbot/assets/146260416/6968b97e-e8af-4c8d-aafc-de06f6b5d1d1)

**Comment by xlvlx** [comment]
screenshot from the second car
![Снимок экрана 2024-06-18 213414](https://github.com/weidengeist/Willowbot/assets/146260416/68f3f0da-0e2e-49ef-a15c-ab958ef20f3e)

**Comment by weidengeist** [comment]
Please do
```
python main_cli --set-config botname [Your bot’s name]
```
again and be sure that there is no `ssl.py` file in your Willowbot directory or any custom `ssl.py` in your Python installation directory.

**Comment by xlvlx** [comment]
at the moment, after changing the bot's nickname in the "config" file, he swears at this:


Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Programs\Willowbot\main_cli.py
 × WARNING! There is no locale for your OS language. Using English.
 ✔ Successfully loaded the logins file.
 ✔ Successfully loaded the IRC configuration file.
 ✔ Successfully loaded the login oauth for 4u**upka.
 ✔ Successfully retrieved
       moderator (4u***pka) ID: 1060702007 and 
       broadcaster (4u***pka) ID: 1060702007.
 × WARNING! No commands available for channel 4u***pka.
 • Trying to import module poll.
     ✔ poll loaded successfully.
 • Trying to import module modChannelInfo.
     ✔ modChannelInfo loaded successfully.
 ✔ Loaded configuration:
       {'language': 'en', 'URL_API': 'https://api.twitch.tv/helix/', 'dir': 'C:\\Users\\213\\AppData\\Roaming\\twitch\\willowbot', 'botname': '4u**upka', 'clientID': 'e5kdpgd2bbnbj1u5gbjpzeq7vsgwup', 'connectionRetries': 10, 'port': 6697, 'server': 'irc.chat.twitch.tv', 'oauth': '5c5iq0uvlqnu8krqtix9p6o2h7ibzd', 'channel': '4u***pka', 'moderatorID': '1060702007', 'broadcasterID': '1060702007'}
 ✔ Pass sent successfully.
 ✔ Bot account name 4u***pka sent successfully.
 ✔ Successfully entered channel
       4u***pka.
21:59:18: :tmi.twitch.tv 001 4u***pka :Welcome, GLHF!

:tmi.twitch.tv 002 4u***pka :Your host is tmi.twitch.tv

:tmi.twitch.tv 003 4u***pka :This server is rather new

:tmi.twitch.tv 004 4u***pka :-

:tmi.twitch.tv 375 4u***pka :-

:tmi.twitch.tv 372 4u***pka :You are in a maze of twisty passages, all alike.

:tmi.twitch.tv 376 4u***pka :>


 ✔ Connected successfully. Waiting for messages on the server.
21:59:18: :4u***pka!4u***pka@4u**upka.tmi.twitch.tv JOIN #4u***pka

:4uqpupka.tmi.twitch.tv 353 4u***pka = #4u***pka :4u***pka

:4uqpupka.tmi.twitch.tv 366 4u***pka #4u***pka :End of /NAMES list


21:59:18: :tmi.twitch.tv CAP * ACK :twitch.tv/tags

:tmi.twitch.tv CAP * ACK :twitch.tv/commands


Traceback (most recent call last):
  File "C:\Programs\Willowbot\main_cli.py", line 70, in <module>
    response = irc.getResponse()
  File "C:\Programs\Willowbot\modules\irc.py", line 122, in getResponse
    if elapsedSinceLatestCheck >= self.config['disconnectCheckInterval']:
KeyError: 'disconnectCheckInterval'

**Comment by xlvlx** [comment]
or can you tell me which Python modules need to be installed? maybe I don't have enough modules to run!

**Comment by weidengeist** [comment]
There has been a key missing in the config template. Please add
```
'disconnectCheckInterval' : 10,
```
to your `config.py` file or simply run `python main_cli.py --configure` and `python main_cli --set-config botname [botname]` again. A fix has been committed to the repository.

**Comment by xlvlx** [comment]
> В шаблоне конфигурации отсутствует ключ. Пожалуйста, добавьте
> 'disconnectCheckInterval' : 10,

Thank you very much, it helped, the bot sees my messages!
