### ISSUE TITLE
settings and correction of the bot code

### ISSUE THREAD

**Issue by xlvlx** [weidengeist/Willowbot#12]
Good time of the day! Do you have the time and desire to fix your bot's code?
Since I'm not a programmer myself and I don't understand much about it (I'm more of a tester with big needs), and I also don't know foreign languages, but I still want to launch your bot and use it completely for my streamer!
the first error that I noticed when creating files, the bot creates three files "config.py " "config_tmp.py " and "logins.py "! As I understood the file itself "config.py " I don't need it because your bot's data with my token is there! (1 photo)
![Снимок экрана 2024-06-20 211953](https://github.com/weidengeist/Willowbot/assets/146260416/fd9ecb00-bbdc-442b-841e-be9a989f14da)

second amendment, I found how to launch a bot on another streamer's channel by launching "main_cgi.py "! We need to add the command "'strimer' : 'nick_strimer'" to the file "config.py ": (2 photo)
![Снимок экрана 2024-06-20 213422](https://github.com/weidengeist/Willowbot/assets/146260416/fa4ae448-2714-4340-9f37-0d4cc1574908)

after that, in the file "basics.py " in line 181, replace "or CONFIG['strimer'].lower()" (3 photo)
![Снимок экрана 2024-06-20 213708](https://github.com/weidengeist/Willowbot/assets/146260416/5d5e0764-7629-4692-9443-0f7c3fe7187b)

**Comment by xlvlx** [comment]
I also have a question: where should I create a file and "iamabot.py "to write a list of commands there so that the bot can read them?

**Comment by weidengeist** [comment]
1. The file `config_tmp.py` must be a residue of having run the bot in a bugged version prior [this commit](https://github.com/weidengeist/Willowbot/commit/ac5b56b645f53c1293d76decf8158fcde2c068f9). `config_tmp.py` is supposed to be renamed to `config.py`, which works flawlessly in my tests. This means that you can safely delete `config_tmp.py`.
2.  Please read the README carefully before using the bot. There is no need to modify the config file and add a `streamer` (correct spelling of `strimer`) key. Run the bot like this: `python main_cli --channel anotherStreamer`. This is documented [here](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#2-initial-setup).
3. The answer for your last question is also covered by the README:
> Besides a directory for the general Willowbot/IRC configuration, this program will create a subdirectory named `commands` in this configuration directory. This is where you have to put the command sets you want your bot to use.

Once again: Please note that issue discussions are not meant for talking about topcis already noted in the README.md or about suggested changes to the code **unless** those changes are **needed to fix bugs, errors, or crashes**. If you want to use Willowbot as a basis for your own bot and you want to modify certain parts, please [create a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) of that project.

**Comment by xlvlx** [comment]
> 1. Этот файл `config_tmp.py`должен быть результатом запуска бота в версии с ошибкой 

it's just that this file causes a connection error as it tries to connect to the streamer 'IAmYourFirstBot'

> 2. Пожалуйста, внимательно прочитайте README перед использованием бота. Нет необходимости изменять файл конфигурации и добавлять ключ `streamer`(правильное написание `strimer`). Запустите бота следующим образом: `python main_cli --channel anotherStreamer`. Это задокументировано [здесь](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#2-initial-setup) .

it is inconvenient for me to launch the bot through the command, since after restarting the laptop, the bot will not be able to automatically reconnect to the channel.

> 3. Ответ на ваш последний вопрос также содержится в README:

where exactly do I create this file and how do I connect to it? 
> Create a file called iamabot.py (as this is the channel where we want to do some tests; please note: Use small letters only!) where you can put your command checks and bot reactions.

> Еще раз: обратите внимание, что обсуждения проблем не предназначены для обсуждения тем, уже отмеченных в README.md, 

Please forgive me, I don't know much about Github.

**Comment by weidengeist** [comment]
1. Which file do you mean? `config_tmp.py`? This file is never used by Willowbot except during the configuration phase. Furthermore, this file is never read, only written to.
2. I don’t see any difference between starting Willowbot by `python main_cli.py` or `python main_cli.py --channel anotherStreamer`. Your problem with hibernating the PC and waking it up again will occur with the former as well as with the latter. You might want to create a desktop shortcut/launcher to start Willowbot with the `--channel` parameter.
3. As you can read in the README.me, which I linked in my previous post and even quoted, you have to put the file in your `commands` directory which is a subdirectory of you Willowbot configuration directory (see your first screenshot). The file is used by launching Willowbot with the `--channel` option, which leads us to point 2 again.

**Comment by xlvlx** [comment]
простите меня, я сам не увидел что сделал фото с данной папкой и ищу её в другом каталоге!
к сожалению создание ярлыков с параметрами я не умею, поэтому выкручиваюсь обычным перекодированием чужих кодов, Большое Вам спасибо, пойду производить тесты...
