### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by LeoAlt8** [weidengeist/Willowbot#14]
Please add a ignore function so that you can tell the bot whose commands not to respond to.

**Comment by weidengeist** [comment]
What is the use case for this feature? Wouldn’t [level differentiation](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#35-level-system) be enough? And why not ban a user who misuses commands in a way that disturbs the community and makes such a feature request relevant?

**Comment by weidengeist** [comment]
The requested feature has been added. For details, please see »List of ignored users« in the »[Initial setup](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#2-initial-setup)« section of the README. A template file for `ignoredUsers.txt` can be found in the repository as well.

Please let me know if anything does not work as expected.
