### ISSUE TITLE
compilation error + missing token data

### ISSUE THREAD

**Issue by xlvlx** [weidengeist/Willowbot#15]
Good afternoon!
1)  I downloaded the updated files, when trying to install it gives an error due to the absence of "," at the end of line 7!
![Снимок экрана 2024-08-11 111406](https://github.com/user-attachments/assets/612b6871-40f0-4784-b72d-2fbd8f0560b4)
![Снимок экрана 2024-08-11 111636](https://github.com/user-attachments/assets/144f93f7-bc11-454f-984d-43e160e64ee2)

after receiving the token, when trying to assign a name to the bot, it gives the error "the file is occupied by another process"
![Снимок экрана 2024-08-11 123051](https://github.com/user-attachments/assets/57ae6a12-d30a-481a-bb48-57834f341bca)
![Снимок экрана 2024-08-11 123141](https://github.com/user-attachments/assets/ff8108d3-4665-4f2f-afac-4e2f5df7aa43)
![Снимок экрана 2024-08-11 123200](https://github.com/user-attachments/assets/0af75765-3da3-42e9-bbcf-b02f68bb04d6)

the token data and the bot's name can only be entered manually!

2) in addition, when trying to create a command "/shoutout", "/ban" or "delete message", it returns the error "missing token"
![Снимок экрана 2024-08-11 120351](https://github.com/user-attachments/assets/07fd00a1-7f04-4472-809f-45e34495deb1)
![Снимок экрана 2024-08-11 120448](https://github.com/user-attachments/assets/7a2244a6-f963-4af9-8ae6-c304ca704fcd)

OS - Windows 10, Python - 3.12

**Comment by weidengeist** [comment]
The first issue has been fixed. Thank you. You can either add the missing comma manually or auto-configure Willowbot again.

Your error message »the file is occupied by another process« is related to the deficient file management of Windows. I’m afraid I can’t help you with that.

Configuration data can be set by command and don’t have to be inserted manually. Please see the [Initial setup](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#2-initial-setup) section in the README: `python main_cli.py --set-config botname iamabot` How to add a token is described during the token generation process. If you have skipped the generation process, please see the [available command line options](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#list-of-command-line-options) about tokens: `python main_cli.py --token add {name} {token}`.

The second issue looks like the `broadcasterID` could not be retrieved successfully. Unfortunately, your screenshot does not show the relevant info. There should be a line like:
```
 ✔ Successfully retrieved
       moderator (abcdef) ID: 123456 and 
       broadcaster (ghijkl) ID: 789012.
```

**Comment by xlvlx** [comment]
![image](https://github.com/user-attachments/assets/9c733dd5-e567-449d-a159-8711e1311d9d)

**Comment by weidengeist** [comment]
As the error message states, your client ID and your OAuth token do not match, so the broadcaster ID and the moderator ID could not be retrieved and commands beginning with a slash won’t be available. This means that the token you have entered in your `logins.py` file has not been created by using Willowbot, but you used another program to do so. Obtaining tokens for Willowbot is described in the README.

**Comment by xlvlx** [comment]
thank you, I understood where I messed up when copying files (the "config.py" file and the "logins.py" file have different token values!)
